name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/azure-dns-manager

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: get_version
        run: |
          # Remove 'v' prefix from tag (v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.get_version.outputs.version }}
            ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/azure-dns-manager
          short-description: "Modern web-based GUI for managing Azure DNS zones"
          readme-filepath: ./README.md
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## Docker Image
            
            Pull the Docker image:
            ```bash
            docker pull ${{ env.DOCKER_IMAGE }}:${{ steps.get_version.outputs.version }}
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            ```
            
            Run the container:
            ```bash
            docker run -d -p 5000:5000 \
              -e AZURE_TENANT_ID=your-tenant-id \
              -e AZURE_CLIENT_ID=your-client-id \
              -e AZURE_CLIENT_SECRET=your-client-secret \
              -e AZURE_SUBSCRIPTION_ID=your-subscription-id \
              -e AZURE_RESOURCE_GROUP=your-resource-group \
              -e AZURE_DNS_ZONE=your-dns-zone \
              ${{ env.DOCKER_IMAGE }}:${{ steps.get_version.outputs.version }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify success
        if: needs.build-and-push.result == 'success'
        run: |
          echo "✅ Docker image successfully built and pushed!"
          echo "🐳 Image: ${{ env.DOCKER_IMAGE }}:latest"
          echo "📦 Version: ${{ github.ref_name }}"
      
      - name: Notify failure
        if: needs.build-and-push.result == 'failure'
        run: |
          echo "❌ Docker build failed!"
          exit 1

